# configuration.yaml

service:
  id: "webitel-service-01"
  addr: "localhost:10155"
  secret: "your-very-secure-secret-key"


log:
  level: "info"
  otel: false
  console: true

postgres:
  dsn: "postgres://postgres:webitel@localhost:6432/webitel"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0


consul:
  addr: "localhost:8500"
  grpc_addr: "127.0.0.1:9999"


pubsub:
  broker_url: "amqp://webitel:webitel@localhost:5673"
  broker_driver: "rabbitmq"
