name: PR (im-contact-service)
run-name: "im-contact-service@pr${{github.event.pull_request.number}}#${{github.run_number}} - ${{github.event.pull_request.title}}"

on:
  pull_request:

permissions: {contents: read}
concurrency:
  group: ${{github.workflow}}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/golang-prepare.yml@v1.0.6
    with:
      development-branch: ${{ github.event.repository.default_branch }}
      triggered-branch: ${{ github.event.pull_request.base.ref }}
  
  checks:
    name: Checks
    needs: [prepare]
    uses: webitel/reusable-workflows/.github/workflows/golang-checks.yml@v1.0.6
    permissions:
      contents: read
      actions: read
      security-events: write